CREATE TABLE IF NOT EXISTS `Customer` (
  `id` INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  `name` varchar(45) NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `Transaction` (
  `id` INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  `customerId` INTEGER NOT NULL,
  `merchantId` varchar(45) NOT NULL,
  `amount` NUMERIC NOT NULL,
  `transactionDate` DATE NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT fk_transaction_customerId FOREIGN KEY(`customerId`) REFERENCES
  Customer(`id`)  
);

CREATE TABLE IF NOT EXISTS `Reward` (
  `id` INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  `rewardPoints` INTEGER NOT NULL,
  `rewardDate` DATE NOT NULL,
  `customerId` INTEGER NOT NULL,
  `transactionId` INTEGER NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT fk_reward_customerId FOREIGN KEY(`customerId`) REFERENCES
  Customer(`id`),
  CONSTRAINT fk_reward_transactionId FOREIGN KEY(`transactionId`) REFERENCES
  Transaction(`id`)  
);